[project]
name = "bienestar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "docxtpl>=0.20.2",
    "pandas>=2.3.3",
    "pdfplumber>=0.11.8",
    "streamlit>=1.51.0",
    "tabula-py>=2.10.0",
]
